spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/dvdrental-spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
